"""Add avg ratig image

Revision ID: 5a27b931f096
Revises: 95b81f8bc4bc
Create Date: 2023-06-13 20:18:42.407416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a27b931f096'
down_revision = '95b81f8bc4bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('avg_rating', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'avg_rating')
    # ### end Alembic commands ###
