"""Update rating

Revision ID: 95b81f8bc4bc
Revises: 9e4736a71b83
Create Date: 2023-06-05 15:17:37.549280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95b81f8bc4bc'
down_revision = '9e4736a71b83'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_ratings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('image_ratings', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_ratings', 'updated_at')
    op.drop_column('image_ratings', 'created_at')
    # ### end Alembic commands ###